name: 'Code Coverage Generator'

on: [ pull_request ]

jobs:
  coverage_reporting:
    name: Coverage_reporting
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      checks: write
      actions: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
    - name: install node modules
      run: npm install
    - name: Test coverage
      uses: mattallty/jest-github-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        # this is just an example, this could be any command that will trigger jest
        test-command: "npm run test:once"
