name: "Code coverage badge generator"

on:
  push:
    branches: [ main ]

jobs:
  coverage_reporting:
    name: Coverage badge generator
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
     - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
    - name: install node modules
      run: npm install
    - name: Generate coverage summary
      run: npm run test:json-summary
    - name: Execute shell
      run: |
        find_color()
        {
            if [ "$1" -lt 80 ]; then
                echo 'red'
            else
                echo 'green'
            fi
        }
        OIFS="$IFS"
        set $(node scripts/coverageReporters.js)
        declare $1
        declare $2
        declare $3
        declare $4
        IFS="$OIFS"
        echo "::group::CoverageReport"
        echo "$1"
        echo "$2"
        echo "$3"
        echo "$4"
        echo "::endgroup::"
        echo "::set-output name=LINES::$(LINES)"
        echo "::set-output name=LINES_COLOR::$(find_color LINES)"
        echo "::set-output name=STATEMENTS::$(STATEMENTS)"
        echo "::set-output name=STATEMENTS_COLOR::$(find_color STATEMENTS)"
        echo "::set-output name=FUNCTIONS::$(FUNCTIONS)"
        echo "::set-output name=FUNCTIONS_COLOR::$(find_color FUNCTIONS)"
        echo "::set-output name=BRANCHES::$(BRANCHES)"
        echo "::set-output name=BRANCHES_COLOR::$(find_color BRANCHES)"
      id: badge-script
    - name: Create lines Badge
      uses: schneegans/dynamic-badges-action@v1.1.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: 8e6024952dacb2bbcc3d828a53cb39b6
        filename: lines.json
        label: Lines
        message: ${{ steps.badge-script.outputs.LINES }}%
        color: ${{ steps.badge-script.outputs.LINES_COLOR }}
