name: "Code coverage badge generator"

on:
  push:
    branches: [ main ]

jobs:
  coverage_reporting:
    name: Coverage repporting
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
    - name: install node modules
      run: npm ci
    - name: Generate coverage summary
      run: npm run test:json-summary
    - name: Execute shell
      run: |
        OIFS="$IFS"
        IFS="|"
        set $(node scripts/coverageReporter.js)
        echo "::group::CoverageBadgeReporter"
        for i; do
          echo "$i"
          echo "::set-output name=${i}"
        done
        echo "::endgroup::"
        IFS="$OIFS"
      id: badge-script
    - name: Create lines Badge
      uses: schneegans/dynamic-badges-action@v1.1.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: ${{ secrets.GIST_ID }}
        filename: lines.json
        label: Lines
        message: ${{ steps.badge-script.outputs.LINES }}%
        color: ${{ steps.badge-script.outputs.LINES_COLOR }}
