name: "PROD Storybook"

on:
  push:
    branches: [ main ]

jobs:
  deploy_storybook:
    name: Deploy storybook
    runs-on: ubuntu-latest
    permissions:
        actions: write
        contents: read
        deployments: write
        pages: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}

    - name: install node modules
      run: npm install

    - name: run jest coverage for storybook integration
      run: npm run test:generate-output

    - name: build storybook
      run: npm run build-storybook

    - name: build and deploy storybook
      uses: JamesIves/github-pages-deploy-action@4.1.7
      with:
          branch: gh-pages
          folder: storybook-static
